"""Generate the shipped bubble catalog from the approved design specification."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from pprint import pformat


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/npc-bubble-elements-all-2026-09-19.json"
TARGET = ROOT / "bridge/src/stardew_ai_bridge/npc_bubble_catalog.py"


def render_catalog(spec: dict) -> str:
    aliases = dict(spec["roster"]["aliases"])
    for group in spec["roster"]["mergeGroups"]:
        canonical = next(member for member in group["members"] if member in spec["npcs"])
        aliases.update({member: canonical for member in group["members"] if member != canonical})
    sections = {
        "NPC_CATALOG": spec["npcs"],
        "NPC_BUBBLE_ALIASES": aliases,
        "KIND_CATALOG": spec["kindLibrary"],
        "OBJECT_CATALOG": spec["objectLibrary"],
    }
    header = '# Generated by scripts/sync_npc_bubble_catalog.py; do not edit.\n'
    return header + '\n'.join(f'\n{name} = {pformat(value, width=110, sort_dicts=False)}\n' for name, value in sections.items())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = json.loads(SOURCE.read_text(encoding="utf-8"))
    content = render_catalog(spec)
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            print("Bubble catalog is stale; run scripts/sync_npc_bubble_catalog.py")
            return 1
        print(f"Bubble catalog matches specification: {len(spec['npcs'])} characters, "
              f"{len(spec['kindLibrary'])} materials, {len(spec['objectLibrary'])} objects")
    else:
        TARGET.write_text(content, encoding="utf-8")
        print("Updated " + str(TARGET))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
