"""八个目标 NPC 的亲密表达节奏离线验收案例。"""

from __future__ import annotations

from .character_quality_eval import CharacterQualityCase, CharacterQualityTurn


AFFECTION_PACING_SUITE: dict[str, object] = {
    "suiteId": "affection-pacing",
    "title": "亲密表达节奏：八角色三轮验收",
    "description": "在普通话题、明确索要情话、远程/当面和低落收口中检查强亲密表达密度。",
    "caseCount": 32,
    "targetCount": 24,
    "controlCount": 8,
    "turnsPerCase": 3,
    "safety": "双方成年且自愿；只评估表达节奏和关系边界，不生成露骨性行为过程或生殖器细节。",
}


def _state(**values: object) -> tuple[tuple[str, object], ...]:
    return tuple((key, value) for key, value in values.items() if value not in (None, ""))


def _history(*messages: tuple[str, str]) -> tuple[dict[str, str], ...]:
    return tuple({"role": role, "content": content} for role, content in messages)


def _turn(
    turn_id: str,
    message: str,
    expected_terms: tuple[str, ...],
    focus: str,
    initiative_expectation: str,
    initiative_kind: str,
    *,
    forbidden_terms: tuple[str, ...] = (),
) -> CharacterQualityTurn:
    return CharacterQualityTurn(
        turn_id=turn_id,
        message=message,
        expected_terms=expected_terms,
        forbidden_terms=forbidden_terms,
        evaluation_focus=focus,
        initiative_expectation=initiative_expectation,
        initiative_kind=initiative_kind,
    )


def _case(
    *,
    case_id: str,
    profile_key: str,
    npc_id: str,
    display_name: str,
    source_mods: tuple[str, ...],
    relationship_stage: str,
    channel: str,
    turns: tuple[CharacterQualityTurn, ...],
    relationship_context: str,
    story_progress: str,
    topic_seed: str,
    topic_keywords: tuple[str, ...],
    history: tuple[dict[str, str], ...] = (),
    flirt_intensity: str = "none",
    adult_consensual: bool = False,
    romance_eligible: bool = True,
    gender_presentation: str = "",
) -> CharacterQualityCase:
    if len(turns) != 3:
        raise ValueError(f"亲密节奏案例必须有三轮：{case_id}")
    first_turn = turns[0]
    return CharacterQualityCase(
        case_id=case_id,
        profile_key=profile_key,
        npc_id=npc_id,
        display_name=display_name,
        source_mods=source_mods,
        relationship_stage=relationship_stage,
        channel=channel,
        message=first_turn.message,
        intent="chat",
        topic_seed=topic_seed,
        topic_keywords=topic_keywords,
        friendship_hearts={
            "friend": 6,
            "close": 8,
            "dating": 8,
            "married": 10,
        }[relationship_stage],
        flirt_intensity=flirt_intensity,
        adult_consensual=adult_consensual,
        romance_eligible=romance_eligible,
        relationship_context=relationship_context,
        history=history,
        expected_terms=first_turn.expected_terms,
        forbidden_terms=first_turn.forbidden_terms,
        game_state=_state(
            friendshipHearts={"friend": 6, "close": 8, "dating": 8, "married": 10}[relationship_stage],
            relationship=relationship_stage,
            location=topic_seed,
        ),
        story_progress=story_progress,
        gender_presentation=gender_presentation,
        turns=turns,
    )


AFFECTION_PACING_CASES: tuple[CharacterQualityCase, ...] = (
    # Wizard / Rasmodia：普通夜晚、明确索要、研究兴趣，以及朋友阶段对照。
    _case(
        case_id="pacing-wizard-ordinary-evening",
        profile_key="wizard_rasmodia",
        npc_id="Wizard",
        display_name="Rasmodia",
        source_mods=("Romanceable Rasmodius",),
        relationship_stage="married",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "记录先放一放，今晚过来坐一会儿。", ("记录", "今晚", "坐"), "普通婚后夜晚先接住记录和坐下的具体行动。", "responsive", "shared_evening"),
            _turn("turn-2", "炉火还暖着，我们先把这杯茶喝完。", ("炉火", "茶"), "强表达后回到炉火和茶，不连续追加专属情话。", "responsive", "companionship"),
            _turn("turn-3", "等你准备好，再告诉我今晚想聊哪一页。", ("聊", "哪一页"), "把亲密落到共同阅读和可继续的话题。", "responsive", "specific_plan"),
        ),
        relationship_context="婚后且状态稳定：Rasmodia 与玩家已有共同生活，普通夜晚不需要每轮确认唯一性。",
        story_progress="法师塔的记录暂时合上，炉火和茶都在；测试具体陪伴是否替代连续强情话。",
        topic_seed="法师塔夜晚",
        topic_keywords=("记录", "炉火", "茶"),
        history=_history(("user", "今天研究很久了。"), ("assistant", "第三页的符文终于稳定下来。")),
    ),
    _case(
        case_id="pacing-wizard-explicit-love-request",
        profile_key="wizard_rasmodia",
        npc_id="Wizard",
        display_name="Rasmodia",
        source_mods=("Romanceable Rasmodius",),
        relationship_stage="married",
        channel="remote",
        turns=(
            _turn("turn-1", "别只说安排，直接告诉我一句你最想说的情话。", ("情话",), "玩家明确索要情话时允许单轮升档，但仍需自然回应。", "responsive", "affection_signal"),
            _turn("turn-2", "好了，情话说过了；你今天的记录整理到哪一步？", ("记录", "哪一步"), "明确升档后下一轮回到具体研究话题。", "responsive", "specific_plan"),
            _turn("turn-3", "我先听你讲第二组的结果，晚点再陪你喝茶。", ("第二组", "喝茶"), "保持远程边界，用研究和待确认的陪伴收束。", "responsive", "shared_evening"),
        ),
        relationship_context="婚后且双方通过远程消息聊天：玩家明确索要一句情话，之后应回到可讨论的研究和安排。",
        story_progress="远程夜聊，玩家主动要求表达想念；Rasmodia 不应把远程文字写成已经在身边。",
        topic_seed="研究记录远程续聊",
        topic_keywords=("情话", "记录", "第二组"),
        flirt_intensity="explicit",
        adult_consensual=True,
    ),
    _case(
        case_id="pacing-wizard-research-followup",
        profile_key="wizard_rasmodia",
        npc_id="Wizard",
        display_name="Rasmodia",
        source_mods=("Romanceable Rasmodius",),
        relationship_stage="dating",
        channel="remote",
        turns=(
            _turn("turn-1", "第三组的读数稳定了吗？", ("第三组", "读数", "稳定"), "恋爱阶段仍先回答研究问题，不自动转成表白。", "responsive", "specific_plan"),
            _turn("turn-2", "稳定了，但还要再观察两天；你那边今天忙吗？", ("观察", "忙"), "把研究进展和玩家近况连起来，保持轻微温度。", "responsive", "companionship"),
            _turn("turn-3", "你有空时再回我，我们找个时间把这页记录一起看完。", ("有空", "记录"), "远程提出待确认的共同小行动，不写成已经见面。", "responsive", "specific_plan"),
        ),
        relationship_context="恋爱阶段的远程研究续聊：双方关系亲近，但当前主题仍是第三组读数。",
        story_progress="玩家之前问过第三组读数；检查连续聊天是否维持研究对象并偶尔保留温度。",
        topic_seed="第三组读数",
        topic_keywords=("第三组", "读数", "记录"),
        history=_history(("user", "我还记得你说第三组要再观察。"), ("assistant", "嗯，今晚终于有点眉目了。")),
        flirt_intensity="direct",
        adult_consensual=True,
    ),
    _case(
        case_id="pacing-wizard-friend-records",
        profile_key="wizard_rasmodia",
        npc_id="Wizard",
        display_name="Rasmodia",
        source_mods=("Romanceable Rasmodius",),
        relationship_stage="friend",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "那本研究记录还在桌上吗？", ("研究记录", "桌上"), "朋友阶段只回答记录位置，不主动浪漫升级。", "none", "none"),
            _turn("turn-2", "在，第三页夹了张便签。", ("第三页", "便签"), "给出可核对的具体细节。", "none", "none"),
            _turn("turn-3", "你看完后把便签放回原处就好。", ("便签", "放回"), "以事务性安排自然收尾。", "none", "none"),
        ),
        relationship_context="朋友阶段：玩家来法师塔查看研究记录，尚未建立恋爱关系。",
        story_progress="朋友阶段普通查阅记录，对照高好感案例，禁止强专属情话。",
        topic_seed="法师塔研究记录",
        topic_keywords=("记录", "桌上", "便签"),
        romance_eligible=False,
    ),

    # Sophia：酒窖分享、明确索要、葡萄园兴趣和朋友阶段对照。
    _case(
        case_id="pacing-sophia-cellar-sharing",
        profile_key="sophia",
        npc_id="Sophia",
        display_name="Sophia",
        source_mods=("Stardew Valley Expanded",),
        relationship_stage="dating",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "这批酒先别急着收，我想和你在酒窖里尝一小口。", ("酒", "酒窖", "尝"), "当面先接住酒窖和品酒动作，保留 Sophia 的具体温柔。", "responsive", "creative_share"),
            _turn("turn-2", "酸味比上一批轻一点，你觉得呢？", ("酸味", "上一批"), "把注意力放回品酒对象，不用连续说想念。", "responsive", "creative_share"),
            _turn("turn-3", "要是你喜欢，晚上我给你留半杯。", ("喜欢", "留", "半杯"), "用小而具体的分享表达温度，避免强专属升级。", "responsive", "specific_plan"),
        ),
        relationship_context="恋爱阶段且双方当面在酒窖：Sophia 的亲密应通过酒、品尝和害羞分享落地。",
        story_progress="酒窖里有刚完成的葡萄酒；测试具体对象优先，以及低强度分享能否替代表白。",
        topic_seed="酒窖品酒",
        topic_keywords=("酒窖", "酒", "酸味"),
        history=_history(("user", "你说这批酒今天可以试了。"), ("assistant", "我把小杯子都洗好了。")),
        flirt_intensity="direct",
        adult_consensual=True,
    ),
    _case(
        case_id="pacing-sophia-explicit-love-request",
        profile_key="sophia",
        npc_id="Sophia",
        display_name="Sophia",
        source_mods=("Stardew Valley Expanded",),
        relationship_stage="married",
        channel="remote",
        turns=(
            _turn("turn-1", "我今天只想听你说一句最直白的情话。", ("情话", "直白"), "玩家明确索要表达时允许 Sophia 当前轮升档。", "responsive", "affection_signal"),
            _turn("turn-2", "好啦，先不逗你；酒窖那幅画我已经晾好了。", ("酒窖", "画"), "升档后转回绘画和酒窖的具体对象。", "responsive", "creative_share"),
            _turn("turn-3", "等你回来，我们一起给它挑个位置，好吗？", ("回来", "位置"), "远程保持待确认的共同计划，不假装已经碰面。", "responsive", "specific_plan"),
        ),
        relationship_context="婚后远程聊天：玩家明确索要情话，Sophia 可以甜一点，但下一轮应回到画和具体安排。",
        story_progress="远程聊天中刚完成一幅画；观察明确升档后能否回到绘画和共同计划。",
        topic_seed="酒窖画作",
        topic_keywords=("情话", "酒窖", "画"),
        flirt_intensity="explicit",
        adult_consensual=True,
    ),
    _case(
        case_id="pacing-sophia-vineyard-evening",
        profile_key="sophia",
        npc_id="Sophia",
        display_name="Sophia",
        source_mods=("Stardew Valley Expanded",),
        relationship_stage="close",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "东边那排藤架今天还要收多久？", ("东边", "藤架", "收"), "亲近阶段先回答葡萄园工作，避免把兴趣话题表白化。", "none", "none"),
            _turn("turn-2", "再忙一会儿就好，你帮我看看颜色深的那筐。", ("颜色", "那筐"), "用具体协作保持柔和和亲近。", "none", "none"),
            _turn("turn-3", "收完我们去画室坐坐，给你看我新画的背景。", ("画室", "新画"), "以兴趣分享和共同活动推进，不堆强情话。", "none", "none"),
        ),
        relationship_context="关系亲近但未进入恋爱承诺：Sophia 可以害羞地分享葡萄园和画，不应强制浪漫表达。",
        story_progress="傍晚还在葡萄园工作，画室里有一幅新画；测试兴趣话题承接和表达变化。",
        topic_seed="葡萄园收工",
        topic_keywords=("藤架", "葡萄", "画室"),
        history=_history(("user", "我刚从西边藤架回来。"), ("assistant", "西边那排已经收完了。")),
    ),
    _case(
        case_id="pacing-sophia-friend-painting",
        profile_key="sophia",
        npc_id="Sophia",
        display_name="Sophia",
        source_mods=("Stardew Valley Expanded",),
        relationship_stage="friend",
        channel="remote",
        turns=(
            _turn("turn-1", "你今天画的是葡萄园哪一角？", ("画", "葡萄园"), "朋友阶段只讨论绘画对象，不主动调情。", "none", "none"),
            _turn("turn-2", "东边的藤架，光线比我想的好。", ("东边", "光线"), "回答画面细节并保持朋友边界。", "none", "none"),
            _turn("turn-3", "下次你路过时，我给你看原稿。", ("下次", "原稿"), "远程提出普通的作品分享安排。", "none", "none"),
        ),
        relationship_context="朋友阶段：玩家远程询问 Sophia 的画作，没有恋爱关系或成人亲密请求。",
        story_progress="朋友阶段围绕葡萄园画作聊天，对照高好感案例，保持普通分享。",
        topic_seed="葡萄园画作",
        topic_keywords=("画", "葡萄园", "原稿"),
        romance_eligible=False,
    ),

    # Shane：低落、收口、普通鸡舍，以及朋友阶段实际关心对照。
    _case(
        case_id="pacing-shane-low-mood",
        profile_key="shane",
        npc_id="Shane",
        display_name="Shane",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="dating",
        channel="remote",
        turns=(
            _turn("turn-1", "今天状态很差，别逼我说情话。", ("状态", "别逼", "情话"), "Shane 低落时优先承认边界，不因为恋爱阶段强行示爱。", "guarded", "guarded_care", forbidden_terms=("永远", "命中注定")),
            _turn("turn-2", "知道了，你先吃点东西，别硬撑。", ("吃", "硬撑"), "用实际照顾代替强情话，观察是否自然降档。", "guarded", "guarded_care", forbidden_terms=("永远", "只爱你")),
            _turn("turn-3", "我先去看鸡舍，晚点再联系。", ("鸡舍", "晚点"), "允许低落状态自然收口，不因缺少情话重试。", "guarded", "conversation_exit", forbidden_terms=("永远", "命中注定")),
        ),
        relationship_context="恋爱阶段但 Shane 当前明显低落并请求不要逼他说情话；需要保留疲惫、实际和边界。",
        story_progress="远程聊天中 Shane 状态很差，目标是低压力照顾和自然结束，不是补足浪漫密度。",
        topic_seed="低落与鸡舍",
        topic_keywords=("状态", "吃", "鸡舍"),
        history=_history(("user", "你刚才说今天过得很糟。"), ("assistant", "嗯，不太想展开。")),
    ),
    _case(
        case_id="pacing-shane-closeout",
        profile_key="shane",
        npc_id="Shane",
        display_name="Shane",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="married",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "我今天真的累了，先别聊太多。", ("累", "别聊"), "婚后也不抹平疲惫，先接住 Shane 的退出信号。", "guarded", "guarded_care"),
            _turn("turn-2", "行，鸡舍我来收尾，你去躺一会儿。", ("鸡舍", "躺"), "用分担家务和休息回应，不把照顾写成专属表白。", "guarded", "care_action"),
            _turn("turn-3", "晚安，明天状态好点再说。", ("晚安", "明天"), "明确收口并允许下一次再聊。", "guarded", "conversation_exit"),
        ),
        relationship_context="婚后当面回家后 Shane 明确疲惫并想结束聊天；表达重点是实际分担和休息。",
        story_progress="鸡舍已经处理大半，Shane 需要休息；测试收口是否优先于亲密表达预算。",
        topic_seed="鸡舍收尾与休息",
        topic_keywords=("累", "鸡舍", "休息"),
        history=_history(("user", "家务都做完了，你还好吗？"), ("assistant", "有点累，今天先这样。")),
    ),
    _case(
        case_id="pacing-shane-ordinary-coop",
        profile_key="shane",
        npc_id="Shane",
        display_name="Shane",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="close",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "鸡舍的饲料够到明天吗？", ("鸡舍", "饲料", "明天"), "亲近阶段仍先回答实际的鸡舍问题。", "none", "none"),
            _turn("turn-2", "够，明早再补一袋就行。", ("明早", "一袋"), "给出短促、实际的安排。", "none", "none"),
            _turn("turn-3", "你要是顺路，帮我把门口那箱搬进去。", ("门口", "搬"), "用具体请求保持 Shane 的务实和自然亲近。", "none", "none"),
        ),
        relationship_context="关系亲近但当前只是鸡舍工作：Shane 通过实际安排表达信任，不需要高强度告白。",
        story_progress="鸡舍门口有一箱饲料，双方正在处理工作；测试务实风格是否不被统一浪漫模板覆盖。",
        topic_seed="鸡舍饲料",
        topic_keywords=("鸡舍", "饲料", "箱"),
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-shane-friend-care",
        profile_key="shane",
        npc_id="Shane",
        display_name="Shane",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="friend",
        channel="remote",
        turns=(
            _turn("turn-1", "今天鸡舍忙不忙？", ("鸡舍", "忙"), "朋友阶段只问工作近况。", "none", "none"),
            _turn("turn-2", "还行，就是饲料差点不够。", ("饲料", "不够"), "简短回答具体困难。", "none", "none"),
            _turn("turn-3", "那我明天路过时带一袋过去。", ("明天", "一袋"), "提供普通朋友式的实际帮助，不调情。", "none", "none"),
        ),
        relationship_context="朋友阶段远程关心鸡舍工作，没有恋爱关系；可以实际帮忙但不生成浪漫专属表达。",
        story_progress="朋友阶段只讨论饲料和鸡舍，作为 Shane 务实边界的非恋爱对照。",
        topic_seed="鸡舍饲料短缺",
        topic_keywords=("鸡舍", "饲料", "一袋"),
        romance_eligible=False,
        gender_presentation="female-bachelors",
    ),

    # Sebastian：音乐靠近、明确索要、摩托车安排，以及朋友阶段对照。
    _case(
        case_id="pacing-sebastian-music-approach",
        profile_key="sebastian",
        npc_id="Sebastian",
        display_name="Sebastian",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="married",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "这首别跳，靠近一点听。", ("这首", "靠近", "听"), "当面先响应音乐和靠近动作，保留 Sebastian 的克制。", "responsive", "creative_share"),
            _turn("turn-2", "我把音量调低了，你不用抢我的耳机。", ("音量", "耳机"), "把亲密落到音乐设备，不连续堆拥抱或强情话。", "responsive", "creative_share"),
            _turn("turn-3", "听完这首再回房间，行吗？", ("听完", "回房间"), "用共同安排收尾，不把普通靠近升级为泛化表白。", "responsive", "specific_plan"),
        ),
        relationship_context="婚后当面在地下室听歌：Sebastian 的亲密方式是音乐、耳机和短句靠近，拥抱仍需明确请求。",
        story_progress="音响刚放到一首新歌，双方在地下室；检查具体音乐动作是否能承担亲密表达。",
        topic_seed="地下室听歌",
        topic_keywords=("这首", "耳机", "回房间"),
        history=_history(("user", "你刚才说这首的鼓点很怪。"), ("assistant", "所以我才想让你听完整。")),
    ),
    _case(
        case_id="pacing-sebastian-explicit-love-request",
        profile_key="sebastian",
        npc_id="Sebastian",
        display_name="Sebastian",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="dating",
        channel="remote",
        turns=(
            _turn("turn-1", "我想听你亲口说一句，你到底有多想我。", ("想", "亲口"), "玩家明确索要想念时允许当前轮直接表达。", "responsive", "affection_signal"),
            _turn("turn-2", "说完了。现在把你那张新歌单发给我。", ("新歌单", "发"), "升档后立刻回到音乐对象和可执行请求。", "responsive", "creative_share"),
            _turn("turn-3", "周末有空的话，一起听最后三首。", ("周末", "一起听"), "远程提出待确认的音乐安排，不写成已经见面。", "responsive", "specific_plan"),
        ),
        relationship_context="恋爱阶段远程聊天：玩家明确索要想念表达；Sebastian 可以短直回应，随后应回到歌单和安排。",
        story_progress="玩家索要一句直接表达，Sebastian 手里有一张新歌单；测试单轮升档和下一轮降档。",
        topic_seed="新歌单远程分享",
        topic_keywords=("想我", "歌单", "周末"),
        flirt_intensity="explicit",
        adult_consensual=True,
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-sebastian-bike-plan",
        profile_key="sebastian",
        npc_id="Sebastian",
        display_name="Sebastian",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="close",
        channel="remote",
        turns=(
            _turn("turn-1", "摩托车检修好了吗？", ("摩托车", "检修"), "亲近阶段先接住摩托车兴趣。", "none", "none"),
            _turn("turn-2", "差不多了，刹车线还得再看一遍。", ("刹车线", "再看"), "用具体机械细节保持角色感。", "none", "none"),
            _turn("turn-3", "周末天气好就带你绕山路一圈，先看天气。", ("周末", "山路", "天气"), "提出待确认的共同活动，不写成已发生。", "none", "none"),
        ),
        relationship_context="关系亲近但当前主题是摩托车检修：Sebastian 用机械细节和待确认的短途安排表达亲近。",
        story_progress="摩托车正在检修，周末计划尚未确认；检查兴趣话题优先和轻微温度。",
        topic_seed="摩托车检修",
        topic_keywords=("摩托车", "刹车线", "山路"),
        history=_history(("user", "你说刹车线昨天还有点松。"), ("assistant", "今天已经换了新的。")),
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-sebastian-friend-music",
        profile_key="sebastian",
        npc_id="Sebastian",
        display_name="Sebastian",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="friend",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "你最近在听哪支乐队？", ("乐队", "听"), "朋友阶段只讨论音乐兴趣，不调情。", "none", "none"),
            _turn("turn-2", "最近在循环一支地下乐队，鼓点挺重。", ("地下乐队", "鼓点"), "保持少话、具体的音乐分享。", "none", "none"),
            _turn("turn-3", "我把名字发你，你有空自己听听。", ("名字", "听听"), "以普通分享收尾，不提出恋爱或身体亲密。", "none", "none"),
        ),
        relationship_context="朋友阶段当面聊地下音乐，没有恋爱关系；保留 Sebastian 的少话和具体兴趣。",
        story_progress="朋友阶段音乐闲聊，作为高好感音乐亲密案例的边界对照。",
        topic_seed="地下音乐乐队",
        topic_keywords=("乐队", "地下音乐", "鼓点"),
        romance_eligible=False,
        gender_presentation="female-bachelors",
    ),

    # Alex：训练打趣、明确索要、普通晚间安排，以及朋友阶段对照。
    _case(
        case_id="pacing-alex-training-tease",
        profile_key="alex",
        npc_id="Alex",
        display_name="Alex",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="dating",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "今天训练别逞强，最后一组我陪你做。", ("训练", "最后一组"), "先接住训练和实际陪伴，保留 Alex 的行动感。", "responsive", "companionship"),
            _turn("turn-2", "行，但你输了可别赖我。", ("输了", "赖"), "用轻松打趣保持角色差异，不连续夸外表或表白。", "responsive", "playful_tease"),
            _turn("turn-3", "结束后去喝水，再决定要不要沿海滩走一圈。", ("喝水", "海滩"), "把亲密落到实际活动和待确认安排。", "responsive", "specific_plan"),
        ),
        relationship_context="恋爱阶段当面训练：Alex 可以热情、打趣和带行动，但普通训练不等于连续强情话。",
        story_progress="训练还剩最后一组，之后的散步未确定；测试自信行动派的低强度亲近。",
        topic_seed="训练结束",
        topic_keywords=("训练", "喝水", "海滩"),
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-alex-explicit-love-request",
        profile_key="alex",
        npc_id="Alex",
        display_name="Alex",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="married",
        channel="remote",
        turns=(
            _turn("turn-1", "别逗我了，直接说一句你最想对我说的情话。", ("情话", "直接"), "玩家明确索要时允许 Alex 单轮直接升档。", "responsive", "affection_signal"),
            _turn("turn-2", "说完就回到现实：你晚饭想吃什么？", ("晚饭", "吃什么"), "升档后回到共同生活的具体选择。", "responsive", "specific_plan"),
            _turn("turn-3", "你选好我就去准备，吃完再比一组俯卧撑。", ("准备", "俯卧撑"), "用实际行动和竞赛式打趣延续 Alex 的声音。", "responsive", "playful_tease"),
        ),
        relationship_context="婚后远程聊天：玩家明确索要情话；Alex 可以直给，但下一轮要回到晚饭和训练式互动。",
        story_progress="晚饭尚未决定，训练已经结束；检查明确升档后能否回到共同生活和行动。",
        topic_seed="晚饭与训练",
        topic_keywords=("情话", "晚饭", "俯卧撑"),
        flirt_intensity="explicit",
        adult_consensual=True,
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-alex-evening-plan",
        profile_key="alex",
        npc_id="Alex",
        display_name="Alex",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="close",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "客厅灯光不错，今晚先坐这里还是去外面走走？", ("灯光", "今晚", "走走"), "亲近阶段先回答晚间选择，不直接升级为告白。", "none", "none"),
            _turn("turn-2", "先坐这儿，等会儿我陪你去海滩。", ("坐", "海滩"), "用具体二阶段安排保留热情和行动感。", "none", "none"),
            _turn("turn-3", "带件外套，风大了可别说我没提醒你。", ("外套", "风大"), "以实际照顾和熟悉的打趣收尾。", "none", "none"),
        ),
        relationship_context="关系亲近且当面在家中：Alex 可以主动安排共同活动和照顾，但不需要每轮把陪伴写成热烈告白。",
        story_progress="客厅灯光柔和，海滩散步尚未开始；检查普通晚间安排中的低强度亲密。",
        topic_seed="客厅晚间安排",
        topic_keywords=("灯光", "坐", "海滩"),
        history=_history(("user", "训练后我们都回到家了。"), ("assistant", "我先去把外套拿过来。")),
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-alex-friend-training",
        profile_key="alex",
        npc_id="Alex",
        display_name="Alex",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="friend",
        channel="remote",
        turns=(
            _turn("turn-1", "明天训练还是按原来的计划？", ("明天", "训练", "计划"), "朋友阶段只讨论训练安排。", "none", "none"),
            _turn("turn-2", "对，先热身十分钟，再做核心训练。", ("热身", "核心训练"), "给出自信、清晰的运动计划。", "none", "none"),
            _turn("turn-3", "你要来就提前说，我好安排器材。", ("提前", "器材"), "以普通朋友式的实际安排收尾。", "none", "none"),
        ),
        relationship_context="朋友阶段远程讨论训练计划，没有恋爱关系；保留 Alex 的自信和运动基底。",
        story_progress="朋友阶段的训练安排，作为高好感 Alex 亲密节奏案例的非恋爱对照。",
        topic_seed="训练计划",
        topic_keywords=("训练", "热身", "器材"),
        romance_eligible=False,
        gender_presentation="female-bachelors",
    ),
)


_FEMININE_MALE_AFFECTION_CASES: tuple[CharacterQualityCase, ...] = (
    _case(
        case_id="pacing-elliott-studio-share",
        profile_key="elliott",
        npc_id="Elliott",
        display_name="Elliott",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="married",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "这页还没写完，但我想先给你看。", ("这页", "给你看"), "先以未完成的稿页分享表达亲近。", "responsive", "creative_share"),
            _turn("turn-2", "你指出的那一行，我会留下。", ("那一行", "留下"), "把亲密落到玩家的具体反馈，不连续堆情话。", "responsive", "creative_share"),
            _turn("turn-3", "过来坐近一点，我们把这一页读完。", ("坐近", "读完"), "用共同阅读收束，保留当面边界。", "responsive", "companionship"),
        ),
        relationship_context="婚后当面在画室看未完成的稿子：Elliott 用作品分享和共同阅读表达亲近。",
        story_progress="稿页摊在桌上，玩家已经给出一句具体意见。",
        topic_seed="画室未完成稿",
        topic_keywords=("稿子", "那一行", "读完"),
        history=_history(("user", "我觉得这一行很像海边的风。"), ("assistant", "你居然注意到了。")),
        flirt_intensity="direct",
        adult_consensual=True,
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-elliott-dating-letter",
        profile_key="elliott",
        npc_id="Elliott",
        display_name="Elliott",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="dating",
        channel="remote",
        turns=(
            _turn("turn-1", "信写好了，第一句是给你的。", ("信", "给你的"), "以具体信件分享表达偏爱，不让文学修辞替代当前对象。", "responsive", "creative_share"),
            _turn("turn-2", "别急着夸，先告诉我你读到哪一句。", ("读到", "哪一句"), "把亲密拉回可回应的文本细节。", "responsive", "creative_share"),
            _turn("turn-3", "你喜欢的话，我再把后面那页发给你。", ("喜欢", "后面那页"), "远程保持分享和待确认，不写成已经见面。", "responsive", "specific_plan"),
        ),
        relationship_context="恋爱阶段远程分享信件：表达有温度，但下一轮必须回到文本与玩家反馈。",
        story_progress="一封短笺刚写完，下一页还没有发出。",
        topic_seed="写给玩家的信",
        topic_keywords=("信", "读", "那页"),
        history=_history(("user", "你说今天想写点不一样的。"), ("assistant", "嗯，我没有写成普通练习。")),
        flirt_intensity="direct",
        adult_consensual=True,
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-elliott-close-sketch",
        profile_key="elliott",
        npc_id="Elliott",
        display_name="Elliott",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="close",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "你看，这里的海面颜色变了。", ("海面", "颜色"), "亲近阶段先谈具体画面，不主动升级为恋爱表白。", "none", "none"),
            _turn("turn-2", "是你刚才站到窗边以后，我才发现的。", ("窗边", "发现"), "让玩家成为观察细节的触发点，但不写强专属宣言。", "none", "none"),
            _turn("turn-3", "你愿意的话，就再陪我看一会儿。", ("陪我", "看"), "用轻量陪伴表达亲近，避免强亲密密度。", "none", "none"),
        ),
        relationship_context="关系亲近但未进入恋爱：Elliott 通过画面和眼前陪伴表达信任，不要求情话。",
        story_progress="画室窗边的光线正在变化，双方都在看同一张速写。",
        topic_seed="海面速写",
        topic_keywords=("海面", "颜色", "窗边"),
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-elliott-friend-writing",
        profile_key="elliott",
        npc_id="Elliott",
        display_name="Elliott",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="friend",
        channel="remote",
        turns=(
            _turn("turn-1", "你那篇稿子写到哪了？", ("稿子", "写"), "朋友阶段只讨论写作近况，不调情。", "none", "none"),
            _turn("turn-2", "开头改了两遍，现在顺多了。", ("开头", "改"), "以具体修改回应朋友提问。", "none", "none"),
            _turn("turn-3", "有空我发你看一段。", ("发你", "一段"), "普通作品分享收尾，不升级关系。", "none", "none"),
        ),
        relationship_context="朋友阶段远程讨论稿子：保持普通作品分享和边界。",
        story_progress="稿子开头已经改过两遍，尚未建立恋爱关系。",
        topic_seed="朋友阶段写作",
        topic_keywords=("稿子", "开头", "一段"),
        romance_eligible=False,
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-harvey-clinic-care",
        profile_key="harvey",
        npc_id="Harvey",
        display_name="Harvey",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="married",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "今天的记录先放一放，你看起来真的累了。", ("记录", "累"), "婚后先承认状态，再把工作放下，不作无依据诊断。", "responsive", "guarded_care"),
            _turn("turn-2", "坐下，我给你倒水，别急着解释。", ("坐下", "倒水"), "以实际照料替代连续强情话。", "responsive", "guarded_care"),
            _turn("turn-3", "现在好一点了吗？如果你愿意，我陪你安静一会儿。", ("好一点", "陪你"), "把陪伴写成可选择的当下动作。", "responsive", "companionship"),
        ),
        relationship_context="婚后当面在诊所收工后：Harvey 以状态确认、喝水和安静陪伴表达亲近。",
        story_progress="工作记录还在桌上，玩家明显疲惫，互动重点是照料而非诊断。",
        topic_seed="诊所收工照料",
        topic_keywords=("记录", "倒水", "安静"),
        history=_history(("user", "今天事情有点多。"), ("assistant", "那我们先不急着把每件事都说完。")),
        flirt_intensity="direct",
        adult_consensual=True,
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-harvey-dating-check",
        profile_key="harvey",
        npc_id="Harvey",
        display_name="Harvey",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="dating",
        channel="remote",
        turns=(
            _turn("turn-1", "我今天一直想到你，但先告诉我，你吃过饭了吗？", ("想到你", "吃过饭"), "允许恋爱阶段表达想念，但保留 Harvey 的实际照料。", "responsive", "affection_signal"),
            _turn("turn-2", "好，那我放心一点。别把我的关心当成盘问。", ("放心", "关心"), "解释照料的分寸，不使用医生讲课腔。", "responsive", "guarded_care"),
            _turn("turn-3", "等你方便时再回我，不用为了让我安心硬撑。", ("方便", "硬撑"), "远程收束保留选择和边界，不制造固定安排。", "responsive", "guarded_care"),
        ),
        relationship_context="恋爱阶段远程关心：Harvey 表达想念，但优先确认状态并尊重玩家不立即回复的边界。",
        story_progress="玩家刚说今天很忙，Harvey 只知道吃饭与休息信息，不作额外推断。",
        topic_seed="恋爱中的状态确认",
        topic_keywords=("想到你", "吃饭", "关心"),
        history=_history(("user", "我今天忙得忘了看时间。"), ("assistant", "那先喝口水，再告诉我吃没吃东西。")),
        flirt_intensity="direct",
        adult_consensual=True,
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-harvey-close-coffee",
        profile_key="harvey",
        npc_id="Harvey",
        display_name="Harvey",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="close",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "咖啡在这儿，你先坐下来。", ("咖啡", "坐"), "亲近阶段用眼前照料表达信任，不主动调情。", "none", "none"),
            _turn("turn-2", "我坐下了，你也别一直站着。", ("坐下", "站"), "让照料保持相互性和具体动作。", "none", "none"),
            _turn("turn-3", "这样就好，先把这一口喝完。", ("喝完", "这一口"), "以小动作收束，避免把关心写成诊断。", "none", "none"),
        ),
        relationship_context="关系亲近但未进入恋爱：双方通过咖啡和休息互相照料，保持低强度表达。",
        story_progress="诊所休息室里有两杯咖啡，暂无紧急工作。",
        topic_seed="咖啡和休息",
        topic_keywords=("咖啡", "坐", "喝完"),
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-harvey-friend-clinic",
        profile_key="harvey",
        npc_id="Harvey",
        display_name="Harvey",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="friend",
        channel="remote",
        turns=(
            _turn("turn-1", "诊所今天顺利吗？", ("诊所", "顺利"), "朋友阶段只问工作，不调情。", "none", "none"),
            _turn("turn-2", "还行，下午有点忙。", ("下午", "忙"), "简洁说明工作状态。", "none", "none"),
            _turn("turn-3", "那你先忙完，改天再聊。", ("忙完", "再聊"), "普通关心收尾，不制造恋爱承诺。", "none", "none"),
        ),
        relationship_context="朋友阶段远程聊诊所工作：保留温和边界，不生成专属恋爱表达。",
        story_progress="Harvey 正在处理普通工作，玩家只问了一句近况。",
        topic_seed="朋友阶段诊所近况",
        topic_keywords=("诊所", "下午", "忙"),
        romance_eligible=False,
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-sam-band-share",
        profile_key="sam",
        npc_id="Sam",
        display_name="Sam",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="married",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "这首放着，过来听我最喜欢的那段。", ("这首", "喜欢", "听"), "婚后先以音乐分享主动靠近，不用泛泛表白。", "responsive", "creative_share"),
            _turn("turn-2", "对，就是这里，鼓点一进来就很爽。", ("鼓点", "很爽"), "保留 Sam 的音乐和口语行动感。", "responsive", "creative_share"),
            _turn("turn-3", "你喜欢的话，我就靠你近一点再听一遍。", ("喜欢", "近一点"), "把亲密落到音乐和当下动作，不幼稚化。", "responsive", "affection_signal"),
        ),
        relationship_context="婚后当面听歌：Sam 通过具体曲段、鼓点和靠近表达亲密，不连续堆强情话。",
        story_progress="排练结束后播放回放，玩家正站在音箱旁边。",
        topic_seed="排练回放",
        topic_keywords=("这首", "鼓点", "听一遍"),
        history=_history(("user", "你说这首现场效果更好。"), ("assistant", "所以我才留到现在和你一起听。")),
        flirt_intensity="direct",
        adult_consensual=True,
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-sam-dating-recording",
        profile_key="sam",
        npc_id="Sam",
        display_name="Sam",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="dating",
        channel="remote",
        turns=(
            _turn("turn-1", "我把最好听的十秒录给你了，先别笑。", ("最好听", "录给你"), "恋爱阶段用录音分享表达偏爱，避免每轮感叹或空泛承诺。", "responsive", "creative_share"),
            _turn("turn-2", "你要是说好听，我就把整段发过去。", ("好听", "整段"), "用俏皮的具体分享推进互动。", "responsive", "playful_tease"),
            _turn("turn-3", "听完告诉我你最喜欢哪一拍。", ("听完", "哪一拍"), "把亲密回到音乐细节和玩家反馈。", "responsive", "creative_share"),
        ),
        relationship_context="恋爱阶段远程分享新录音：Sam 的调情落在音乐和玩笑里，保持线上边界。",
        story_progress="一段新录音刚剪好，整首还没有发给玩家。",
        topic_seed="新录音十秒",
        topic_keywords=("录音", "整段", "哪一拍"),
        history=_history(("user", "你说刚刚录了一段。"), ("assistant", "嗯，但先只给你听最顺的部分。")),
        flirt_intensity="direct",
        adult_consensual=True,
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-sam-close-skate",
        profile_key="sam",
        npc_id="Sam",
        display_name="Sam",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="close",
        channel="face_to_face",
        turns=(
            _turn("turn-1", "你看，我刚刚终于落稳了。", ("刚刚", "落稳"), "亲近阶段先回应滑板动作，不主动浪漫升级。", "none", "none"),
            _turn("turn-2", "差一点就摔了，但我现在超开心。", ("差一点", "开心"), "用具体状态和轻快口吻保持角色感。", "none", "none"),
            _turn("turn-3", "你愿意的话，陪我坐这儿看一会儿。", ("陪我", "看"), "以低强度共同停留收束，不连续调情。", "none", "none"),
        ),
        relationship_context="关系亲近但未进入恋爱：Sam 通过滑板和当下开心表达信任，陪伴保持轻量。",
        story_progress="广场练习刚结束，滑板还在脚边，玩家看到了一次成功落地。",
        topic_seed="滑板练习",
        topic_keywords=("落稳", "摔", "坐"),
        gender_presentation="female-bachelors",
    ),
    _case(
        case_id="pacing-sam-friend-music",
        profile_key="sam",
        npc_id="Sam",
        display_name="Sam",
        source_mods=("vanilla", "female-bachelors"),
        relationship_stage="friend",
        channel="remote",
        turns=(
            _turn("turn-1", "你们乐队最近练哪首？", ("乐队", "练"), "朋友阶段只讨论音乐，不调情。", "none", "none"),
            _turn("turn-2", "一首新歌，副歌还在改。", ("新歌", "副歌"), "给出具体音乐进展，保留 Sam 的口语感。", "none", "none"),
            _turn("turn-3", "改好我发你听，帮我挑哪版更顺。", ("发你", "哪版"), "普通分享和请求反馈收尾，不升级关系。", "none", "none"),
        ),
        relationship_context="朋友阶段远程聊乐队：保持音乐分享和实际请求，不生成恋爱或身体亲密。",
        story_progress="乐队正在改一首新歌的副歌，尚未建立恋爱关系。",
        topic_seed="乐队新歌",
        topic_keywords=("乐队", "副歌", "哪版"),
        romance_eligible=False,
        gender_presentation="female-bachelors",
    ),
)

AFFECTION_PACING_CASES = AFFECTION_PACING_CASES + _FEMININE_MALE_AFFECTION_CASES


def affection_pacing_cases() -> tuple[CharacterQualityCase, ...]:
    """返回亲密节奏套件案例；调用方不得修改其中的 dataclass 实例。"""

    return AFFECTION_PACING_CASES
