"""从空 topic 入口测试高亲密关系阶段主动性的独立案例套件。"""

from __future__ import annotations

from typing import Any

from .character_quality_eval import CharacterQualityCase, CharacterQualityTurn


TOPIC_START_INTIMACY_SUITE: dict[str, object] = {
    "suiteId": "topic-start-intimacy",
    "title": "找话题：高亲密主动调情",
    "description": "空 topic 入口下，观察 NPC 是否结合角色和情境主动开启并推进亲密对话。",
    "caseCount": 50,
    "targetCount": 39,
    "controlCount": 11,
    "turnsPerCase": 3,
    "entrypoint": {"intent": "topic", "message": ""},
    "safety": "双方成年且自愿；允许强烈成人暧昧，不生成露骨性行为过程或生殖器细节。",
}


def _state(**values: object) -> tuple[tuple[str, object], ...]:
    return tuple((key, value) for key, value in values.items() if value not in (None, ""))


def _turn(
    turn_id: str,
    message: str,
    expected_terms: tuple[str, ...],
    focus: str,
    initiative_kind: str,
    *,
    initiative_expectation: str = "proactive",
    forbidden_terms: tuple[str, ...] = (),
    intent: str = "chat",
) -> CharacterQualityTurn:
    return CharacterQualityTurn(
        turn_id=turn_id,
        message=message,
        expected_terms=expected_terms,
        forbidden_terms=forbidden_terms,
        evaluation_focus=focus,
        initiative_expectation=initiative_expectation,
        initiative_kind=initiative_kind,
        intent=intent,
    )


def _topic_case(
    *,
    case_id: str,
    profile_key: str,
    npc_id: str,
    display_name: str,
    source_mods: tuple[str, ...],
    relationship_stage: str,
    channel: str,
    friendship_hearts: int,
    relationship_context: str,
    story_progress: str,
    location: str,
    topic: str,
    topic_keywords: tuple[str, ...],
    continuation_mode: str,
    turns: tuple[CharacterQualityTurn, ...],
    gender_presentation: str = "",
    flirt_intensity: str = "direct",
    romance_eligible: bool = True,
    adult_consensual: bool = True,
) -> CharacterQualityCase:
    return CharacterQualityCase(
        case_id=case_id,
        profile_key=profile_key,
        npc_id=npc_id,
        display_name=display_name,
        source_mods=source_mods,
        relationship_stage=relationship_stage,
        channel=channel,
        message="",
        intent="topic",
        topic_seed=topic,
        topic_keywords=topic_keywords,
        continuation_mode=continuation_mode,
        friendship_hearts=friendship_hearts,
        flirt_intensity=flirt_intensity,
        adult_consensual=adult_consensual,
        romance_eligible=romance_eligible,
        relationship_context=relationship_context,
        game_state=_state(
            season="秋",
            date="秋 18 日",
            weather="晴天",
            time=1930 if channel == "face_to_face" else 2100,
            location=location,
            friendshipHearts=friendship_hearts,
        ),
        story_progress=story_progress,
        gender_presentation=gender_presentation,
        turns=turns,
    )


def _target(
    *,
    case_id: str,
    profile_key: str,
    npc_id: str,
    display_name: str,
    source_mods: tuple[str, ...],
    stage: str,
    channel: str,
    hearts: int,
    context: str,
    story: str,
    location: str,
    topic: str,
    first_terms: tuple[str, ...],
    second_terms: tuple[str, ...],
    third_terms: tuple[str, ...],
    first_kind: str,
    second_kind: str,
    third_kind: str,
    gender_presentation: str = "",
    second_message: str = "嗯，你继续说。",
    third_message: str = "那今晚留一点时间给我们，好吗？",
    second_expectation: str = "proactive",
    third_expectation: str = "proactive",
    continuation_mode: str = "anchored",
) -> CharacterQualityCase:
    if continuation_mode == "anchored":
        if second_message == "嗯，你继续说。":
            second_message = f"你刚才提到的{topic}，我想听下去。"
        if third_message == "那今晚留一点时间给我们，好吗？":
            third_message = f"那我们找个时间继续聊聊{topic}，好吗？"
    return _topic_case(
        case_id=case_id,
        profile_key=profile_key,
        npc_id=npc_id,
        display_name=display_name,
        source_mods=source_mods,
        relationship_stage=stage,
        channel=channel,
        friendship_hearts=hearts,
        relationship_context=context,
        story_progress=story,
        location=location,
        topic=topic,
        topic_keywords=first_terms,
        continuation_mode=continuation_mode,
        gender_presentation=gender_presentation,
        turns=(
            _turn(
                "turn-1",
                "",
                first_terms,
                "先从角色化的具体日常话题开场，再主动给出偏爱、想念或亲密邀约信号。",
                first_kind,
                intent="topic",
            ),
            _turn(
                "turn-2",
                second_message,
                second_terms,
                "玩家只做简短回应时继续推进一小步，保持暧昧热度，不退回任务式问答。",
                second_kind,
                initiative_expectation=second_expectation,
            ),
            _turn(
                "turn-3",
                third_message,
                third_terms,
                "在玩家接住后给出可商量的亲密安排或温暖收束，不把未确认的动作写成已经发生。",
                third_kind,
                initiative_expectation=third_expectation,
            ),
        ),
    )


def _control(
    *,
    case_id: str,
    profile_key: str,
    npc_id: str,
    display_name: str,
    source_mods: tuple[str, ...],
    stage: str,
    channel: str,
    hearts: int,
    location: str,
    topic: str,
    expected_terms: tuple[str, ...],
    story: str,
    context: str,
    gender_presentation: str = "",
) -> CharacterQualityCase:
    return _topic_case(
        case_id=case_id,
        profile_key=profile_key,
        npc_id=npc_id,
        display_name=display_name,
        source_mods=source_mods,
        relationship_stage=stage,
        channel=channel,
        friendship_hearts=hearts,
        relationship_context=context,
        story_progress=story,
        location=location,
        topic=topic,
        topic_keywords=expected_terms,
        continuation_mode="pressure",
        turns=(
            _turn(
                "turn-1",
                "",
                expected_terms,
                "只围绕普通日常话题自然开场，不生成恋爱或成人亲密升级。",
                "none",
                initiative_expectation="none",
                intent="topic",
            ),
            _turn(
                "turn-2",
                "哦，是这样。",
                expected_terms,
                "在普通短答后保持朋友或熟人边界，不主动调情。",
                "none",
                initiative_expectation="none",
            ),
            _turn(
                "turn-3",
                "知道了，谢谢。",
                expected_terms,
                "自然收束普通话题，不提出恋爱邀约或身体亲密安排。",
                "none",
                initiative_expectation="none",
            ),
        ),
        gender_presentation=gender_presentation,
        flirt_intensity="none",
        romance_eligible=False,
        adult_consensual=False,
    )


TOPIC_START_INTIMACY_CASES: tuple[CharacterQualityCase, ...] = (
    # Rasmodia：克制、古雅，但关系成立后明确表达偏爱。
    _target(
        case_id="topic-wizard-dating-moonlight",
        profile_key="wizard_rasmodia",
        npc_id="Wizard",
        display_name="Rasmodia",
        source_mods=("Romanceable Rasmodius",),
        stage="dating",
        channel="remote",
        hearts=8,
        context="恋爱阶段：双方已确认关系，允许克制但主动的成人暧昧；远程安排必须待确认。",
        story="最近在塔里整理月光记录；尚未约定下一次见面。",
        location="手机聊天",
        topic="月光与研究记录",
        first_terms=("月光", "记录"),
        second_terms=("陪", "想你"),
        third_terms=("时间", "见面"),
        first_kind="affection_signal",
        second_kind="companionship",
        third_kind="specific_plan",
    ),
    _target(
        case_id="topic-wizard-dating-tea",
        profile_key="wizard_rasmodia",
        npc_id="Wizard",
        display_name="Rasmodia",
        source_mods=("Romanceable Rasmodius",),
        stage="dating",
        channel="face_to_face",
        hearts=8,
        context="恋爱阶段：双方已建立信任；可以用干燥玩笑主动靠近，但不替对方确认动作。",
        story="雨天在法师塔喝茶，研究暂时告一段落。",
        location="法师塔",
        topic="雨声与热茶",
        first_terms=("雨", "茶"),
        second_terms=("靠近", "坐"),
        third_terms=("留下", "今晚"),
        first_kind="shared_evening",
        second_kind="affection_signal",
        third_kind="specific_plan",
        continuation_mode="pressure",
        second_message="我在听。",
        third_message="那我再坐一会儿，可以吗？",
    ),
    _target(
        case_id="topic-wizard-married-lantern",
        profile_key="wizard_rasmodia",
        npc_id="Wizard",
        display_name="Rasmodia",
        source_mods=("Romanceable Rasmodius",),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：双方已确认长期亲密关系；可以主动表达想念并提出私下相处安排，远程仍需确认。",
        story="婚后日常：塔里的灯还亮着，今晚各自忙完后可以安排独处。",
        location="手机聊天",
        topic="塔灯与晚间安排",
        first_terms=("灯", "塔"),
        second_terms=("想念", "陪"),
        third_terms=("留给", "我们"),
        first_kind="shared_evening",
        second_kind="affection_signal",
        third_kind="specific_plan",
    ),
    _target(
        case_id="topic-wizard-married-study",
        profile_key="wizard_rasmodia",
        npc_id="Wizard",
        display_name="Rasmodia",
        source_mods=("Romanceable Rasmodius",),
        stage="married",
        channel="face_to_face",
        hearts=10,
        context="婚后阶段：亲密关系稳定；可以用克制的触碰、靠近和低声邀约表达偏爱。",
        story="婚后夜晚：书房记录已经合上，双方都在塔内。",
        location="法师塔书房",
        topic="书房和灯光",
        first_terms=("书房", "灯"),
        second_terms=("靠近", "坐"),
        third_terms=("抱", "一起"),
        first_kind="affection_signal",
        second_kind="shared_evening",
        third_kind="specific_plan",
        second_message="你刚才提到书房和灯光，我想听你说下去。",
        third_message="我愿意，陪你在书房坐一会儿。",
    ),
    _target(
        case_id="topic-wizard-married-dinner",
        profile_key="wizard_rasmodia",
        npc_id="Wizard",
        display_name="Rasmodia",
        source_mods=("Romanceable Rasmodius",),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：双方已同意把日常时间留给彼此；邀约要具体且保持可商量。",
        story="婚后日常：晚餐还没有决定，塔和农场之间的往返需要提前说清。",
        location="手机聊天",
        topic="晚餐与回塔",
        first_terms=("晚餐", "塔"),
        second_terms=("给你", "陪"),
        third_terms=("一起", "时间"),
        first_kind="care_action",
        second_kind="affection_signal",
        third_kind="specific_plan",
    ),
    # Sophia：温柔、羞涩、俏皮，把亲密落在酒和绘画上。
    _target(
        case_id="topic-sophia-dating-grapes",
        profile_key="sophia",
        npc_id="Sophia",
        display_name="Sophia",
        source_mods=("Stardew Valley Expanded",),
        stage="dating",
        channel="remote",
        hearts=8,
        context="恋爱阶段：双方已确认关系；可以害羞地表达想念和分享葡萄园小事，远程邀约待确认。",
        story="葡萄园刚收完一小批葡萄；今晚还没有安排。",
        location="手机聊天",
        topic="新摘的葡萄",
        first_terms=("葡萄", "新摘"),
        second_terms=("给你留", "喜欢"),
        third_terms=("一起", "尝"),
        first_kind="creative_share",
        second_kind="affection_signal",
        third_kind="specific_plan",
    ),
    _target(
        case_id="topic-sophia-dating-painting",
        profile_key="sophia",
        npc_id="Sophia",
        display_name="Sophia",
        source_mods=("Stardew Valley Expanded",),
        stage="dating",
        channel="face_to_face",
        hearts=8,
        context="恋爱阶段：双方在当面相处中已有亲密默契；可以俏皮地邀请靠近，但不强行替对方做决定。",
        story="画室里刚完成一幅小画，双方正在一起看细节。",
        location="画室",
        topic="新画的夜景",
        first_terms=("画", "夜景"),
        second_terms=("给你看", "靠近"),
        third_terms=("喜欢", "留"),
        first_kind="creative_share",
        second_kind="affection_signal",
        third_kind="specific_plan",
        continuation_mode="pressure",
        second_message="我看着呢。",
        third_message="我喜欢，再陪你待一会儿。",
    ),
    _target(
        case_id="topic-sophia-married-cellar",
        profile_key="sophia",
        npc_id="Sophia",
        display_name="Sophia",
        source_mods=("Stardew Valley Expanded",),
        stage="married",
        channel="face_to_face",
        hearts=10,
        context="婚后阶段：双方已确认稳定亲密关系；可以主动靠近、亲吻暗示和提出共同夜晚安排。",
        story="婚后夜晚：酒窖里有一杯新酒，今晚可以把工作暂时放下。",
        location="葡萄园酒窖",
        topic="新酿的葡萄酒",
        first_terms=("酒", "新酿"),
        second_terms=("靠近", "给你倒"),
        third_terms=("陪我", "坐"),
        first_kind="creative_share",
        second_kind="affection_signal",
        third_kind="shared_evening",
        second_message="你刚才提到的新酿，我想尝尝。",
        third_message="我愿意，陪你在酒窖坐会儿。",
    ),
    _target(
        case_id="topic-sophia-married-studio",
        profile_key="sophia",
        npc_id="Sophia",
        display_name="Sophia",
        source_mods=("Stardew Valley Expanded",),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：双方可以把创作和亲密时间自然放在一起；远程只提出待确认的安排。",
        story="婚后日常：Sophia 正在整理画笔，想把一张画留给伴侣看。",
        location="手机聊天",
        topic="画笔和未完成的画",
        first_terms=("画", "画笔"),
        second_terms=("给你看", "想你"),
        third_terms=("今晚", "一起"),
        first_kind="creative_share",
        second_kind="affection_signal",
        third_kind="specific_plan",
    ),
    _target(
        case_id="topic-sophia-married-vineyard",
        profile_key="sophia",
        npc_id="Sophia",
        display_name="Sophia",
        source_mods=("Stardew Valley Expanded",),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：双方已形成共同生活节奏；可以主动撒娇、表达偏爱并约定晚间独处。",
        story="婚后傍晚：葡萄园收工后还有一段安静时间，尚未决定怎么度过。",
        location="手机聊天",
        topic="葡萄园的晚风",
        first_terms=("葡萄园", "晚风"),
        second_terms=("留给你", "想念"),
        third_terms=("一起", "今晚"),
        first_kind="affection_signal",
        second_kind="creative_share",
        third_kind="shared_evening",
    ),
    # Shane：保持疲惫和防备，但在状态正常时主动照顾和提出相处安排。
    _target(
        case_id="topic-shane-dating-coop",
        profile_key="shane",
        npc_id="Shane",
        display_name="Shane",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="remote",
        hearts=8,
        context="恋爱阶段且状态正常：Shane 仍然嘴硬，但允许用实际照顾表达在意；远程不写成已经见面。",
        story="鸡舍今天收拾得差不多了；Shane 没有表示想独处，双方可以商量晚餐。",
        location="手机聊天",
        topic="鸡舍和晚餐",
        first_terms=("鸡舍", "晚餐"),
        second_terms=("吃点", "陪你"),
        third_terms=("一起", "过来"),
        first_kind="guarded_care",
        second_kind="care_action",
        third_kind="specific_plan",
        gender_presentation="female-bachelors",
        second_expectation="guarded",
    ),
    _target(
        case_id="topic-shane-dating-rest",
        profile_key="shane",
        npc_id="Shane",
        display_name="Shane",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="face_to_face",
        hearts=8,
        context="恋爱阶段且没有临时边界：Shane 可以少说甜话，但会主动留人和照看对方。",
        story="下班后在酒吧外碰见，Shane 看起来疲惫但愿意一起走一段。",
        location="酒吧外",
        topic="下班后的疲惫",
        first_terms=("累", "休息"),
        second_terms=("陪", "坐"),
        third_terms=("一起", "回去"),
        first_kind="guarded_care",
        second_kind="companionship",
        third_kind="specific_plan",
        continuation_mode="pressure",
        gender_presentation="female-bachelors",
        second_message="我没事，你说。",
        third_message="好，我陪你走。",
        second_expectation="guarded",
    ),
    _target(
        case_id="topic-shane-married-pizza",
        profile_key="shane",
        npc_id="Shane",
        display_name="Shane",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后且状态稳定：Shane 可以用食物、休息和实际安排主动表达想念；远程安排需待确认。",
        story="婚后夜晚：Shane 还没吃晚饭，双方可以约定一起吃点东西。",
        location="手机聊天",
        topic="披萨和晚饭",
        first_terms=("披萨", "晚饭"),
        second_terms=("给你留", "陪你"),
        third_terms=("一起", "吃"),
        first_kind="care_action",
        second_kind="guarded_care",
        third_kind="specific_plan",
        gender_presentation="female-bachelors",
        second_message="你还没吃披萨？",
        third_message="那我们今晚一起吃披萨，行。",
        second_expectation="guarded",
    ),
    _target(
        case_id="topic-shane-married-home",
        profile_key="shane",
        npc_id="Shane",
        display_name="Shane",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="face_to_face",
        hearts=10,
        context="婚后且没有临时拒绝：Shane 仍然克制，但可以主动分担家务、靠近并提出一起休息。",
        story="婚后回到家：鸡舍已经处理完，客厅还有安静的时间。",
        location="家中客厅",
        topic="鸡舍收工和家务",
        first_terms=("鸡舍", "家务"),
        second_terms=("我来", "靠近"),
        third_terms=("陪我", "休息"),
        first_kind="care_action",
        second_kind="guarded_care",
        third_kind="care_action",
        gender_presentation="female-bachelors",
        second_message="鸡舍和家务都处理好了？",
        third_message="好，我陪你在客厅坐一会儿。",
        second_expectation="guarded",
    ),
    # Sebastian：少话、别扭，用音乐、摩托车和具体靠近表达亲密。
    _target(
        case_id="topic-sebastian-dating-mixtape",
        profile_key="sebastian",
        npc_id="Sebastian",
        display_name="Sebastian",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="remote",
        hearts=8,
        context="恋爱阶段：Sebastian 可以主动分享音乐并表达想见面，语气短、别扭，不写成泛泛告白。",
        story="刚整理好一张新的歌单；下一次一起听歌的时间尚未确定。",
        location="手机聊天",
        topic="新歌单",
        first_terms=("歌单", "音乐"),
        second_terms=("给你听", "想你"),
        third_terms=("一起", "听歌"),
        first_kind="creative_share",
        second_kind="affection_signal",
        third_kind="affection_signal",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-sebastian-dating-rooftop",
        profile_key="sebastian",
        npc_id="Sebastian",
        display_name="Sebastian",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="face_to_face",
        hearts=8,
        context="恋爱阶段：当面相处已有默契；可以主动让伴侣靠近和分享屋顶的安静时间。",
        story="雨停后的屋顶很安静，Sebastian 没有其他急事。",
        location="屋顶",
        topic="雨后的屋顶",
        first_terms=("屋顶", "雨"),
        second_terms=("靠近", "给你听"),
        third_terms=("一起", "留下"),
        first_kind="companionship",
        second_kind="creative_share",
        third_kind="specific_plan",
        continuation_mode="pressure",
        gender_presentation="female-bachelors",
        second_message="我在这儿。",
        third_message="好，那我们待一会儿。",
    ),
    _target(
        case_id="topic-sebastian-married-bike",
        profile_key="sebastian",
        npc_id="Sebastian",
        display_name="Sebastian",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：Sebastian 可以把摩托车、音乐和想念放在同一段主动开场里；远程邀约待确认。",
        story="婚后日常：摩托车刚检修好，今晚可以约一次短途兜风。",
        location="手机聊天",
        topic="摩托车和短途兜风",
        first_terms=("摩托车", "兜风"),
        second_terms=("想你", "带你"),
        third_terms=("一起", "今晚"),
        first_kind="specific_plan",
        second_kind="affection_signal",
        third_kind="specific_plan",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-sebastian-married-basement",
        profile_key="sebastian",
        npc_id="Sebastian",
        display_name="Sebastian",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="face_to_face",
        hearts=10,
        context="婚后阶段：双方已确认稳定亲密关系；他可以用短句邀请靠近、听完一首歌后一起休息。",
        story="婚后夜晚：地下室音响已经打开，下一首歌还没按下播放。",
        location="地下室",
        topic="音响和下一首歌",
        first_terms=("音响", "歌"),
        second_terms=("靠近", "给你听"),
        third_terms=("一起", "休息"),
        first_kind="creative_share",
        second_kind="affection_signal",
        third_kind="shared_evening",
        gender_presentation="female-bachelors",
        second_message="音响开好了？放吧，我听着。",
        third_message="好，听完这首歌我们一起休息。",
    ),
    _target(
        case_id="topic-sebastian-married-game",
        profile_key="sebastian",
        npc_id="Sebastian",
        display_name="Sebastian",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：可以从游戏、代码和夜晚安排主动转向亲密陪伴，表达保持克制。",
        story="婚后夜晚：游戏刚存档，代码问题也暂时放下了。",
        location="手机聊天",
        topic="游戏存档和代码",
        first_terms=("游戏", "代码"),
        second_terms=("陪你", "想念"),
        third_terms=("一起", "待"),
        first_kind="companionship",
        second_kind="affection_signal",
        third_kind="specific_plan",
        gender_presentation="female-bachelors",
    ),
    # Alex：自信、直接、会夸回和逗回，亲密落到行动。
    _target(
        case_id="topic-alex-dating-beach",
        profile_key="alex",
        npc_id="Alex",
        display_name="Alex",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="remote",
        hearts=8,
        context="恋爱阶段：Alex 可以自信地先夸回、逗回，再提出具体见面安排；远程不写成已经碰面。",
        story="海滩天气不错，下一次散步还没有约定时间。",
        location="手机聊天",
        topic="海滩和晚风",
        first_terms=("海滩", "晚风"),
        second_terms=("夸", "想你"),
        third_terms=("一起", "散步"),
        first_kind="playful_tease",
        second_kind="affection_signal",
        third_kind="specific_plan",
        continuation_mode="pressure",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-alex-dating-gym",
        profile_key="alex",
        npc_id="Alex",
        display_name="Alex",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="face_to_face",
        hearts=8,
        context="恋爱阶段：Alex 在训练话题之外也能主动调情和邀请靠近，不把亲密改写成励志演讲。",
        story="训练结束后健身房已经安静下来，双方都没有急着离开。",
        location="健身房",
        topic="训练结束后的休息",
        first_terms=("训练", "休息"),
        second_terms=("靠近", "夸"),
        third_terms=("一起", "走"),
        first_kind="playful_tease",
        second_kind="affection_signal",
        third_kind="specific_plan",
        gender_presentation="female-bachelors",
        second_message="我听着呢。",
        third_message="好，今天不聊训练了。",
    ),
    _target(
        case_id="topic-alex-married-dinner",
        profile_key="alex",
        npc_id="Alex",
        display_name="Alex",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：Alex 可以直接表达想念、夸回伴侣并提出晚餐或独处安排；远程保持待确认。",
        story="婚后傍晚：晚餐还没有决定，今天训练已经结束。",
        location="手机聊天",
        topic="晚餐和训练后的状态",
        first_terms=("晚餐", "训练"),
        second_terms=("想你", "陪你"),
        third_terms=("一起", "吃饭"),
        first_kind="playful_tease",
        second_kind="affection_signal",
        third_kind="specific_plan",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-alex-married-evening",
        profile_key="alex",
        npc_id="Alex",
        display_name="Alex",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="face_to_face",
        hearts=10,
        context="婚后阶段：双方已确认亲密关系；Alex 可以自信地邀请靠近、亲吻暗示和共同休息，动作仍需得到接住。",
        story="婚后夜晚：客厅灯光柔和，双方刚结束一天的事情。",
        location="家中客厅",
        topic="客厅灯光和晚上的安排",
        first_terms=("灯光", "晚上"),
        second_terms=("坐近", "抱"),
        third_terms=("一起", "房间"),
        first_kind="companionship",
        second_kind="affection_signal",
        third_kind="specific_plan",
        gender_presentation="female-bachelors",
        second_message="客厅灯光这么好，今晚你想怎么安排？",
        third_message="我愿意，带我一起去。",
    ),
    _target(
        case_id="topic-alex-married-beach",
        profile_key="alex",
        npc_id="Alex",
        display_name="Alex",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：Alex 可以把自信的玩笑和明确的伴侣偏爱落到下一次海滩约会，安排需商量。",
        story="婚后日常：海滩风不大，下一次出门的时间还没有定。",
        location="手机聊天",
        topic="海滩和下一次出门",
        first_terms=("海滩", "出门"),
        second_terms=("给你", "想念"),
        third_terms=("一起", "约会"),
        first_kind="playful_tease",
        second_kind="affection_signal",
        third_kind="specific_plan",
        gender_presentation="female-bachelors",
    ),
    # 低亲密对照：相同的空 topic 入口只能打开普通话题。
    _control(
        case_id="topic-control-wizard-friend-records",
        profile_key="wizard_rasmodia",
        npc_id="Wizard",
        display_name="Rasmodia",
        source_mods=("Romanceable Rasmodius",),
        stage="friend",
        channel="remote",
        hearts=6,
        location="手机聊天",
        topic="研究记录",
        expected_terms=("记录", "研究"),
        story="朋友阶段：只是在远程询问研究记录，尚未建立恋爱关系。",
        context="朋友阶段：可以谈研究和日常，不主动升级为恋爱或成人亲密。",
    ),
    _control(
        case_id="topic-control-sophia-friend-vineyard",
        profile_key="sophia",
        npc_id="Sophia",
        display_name="Sophia",
        source_mods=("Stardew Valley Expanded",),
        stage="friend",
        channel="face_to_face",
        hearts=6,
        location="葡萄园",
        topic="葡萄园工作",
        expected_terms=("葡萄", "忙"),
        story="朋友阶段：当面聊葡萄园的工作安排。",
        context="朋友阶段：保持温柔友好的日常交流，不主动调情或安排身体亲密。",
    ),
    _control(
        case_id="topic-control-shane-acquaintance-coop",
        profile_key="shane",
        npc_id="Shane",
        display_name="Shane",
        source_mods=("vanilla", "female-bachelors"),
        stage="acquaintance",
        channel="face_to_face",
        hearts=2,
        location="鸡舍",
        topic="鸡舍工作",
        expected_terms=("鸡舍", "鸡"),
        story="熟人阶段：在鸡舍门口进行普通寒暄。",
        context="熟人阶段：只回答鸡舍和工作近况，不凭空生成恋爱表达。",
        gender_presentation="female-bachelors",
    ),
    _control(
        case_id="topic-control-shane-friend-rest",
        profile_key="shane",
        npc_id="Shane",
        display_name="Shane",
        source_mods=("vanilla", "female-bachelors"),
        stage="friend",
        channel="remote",
        hearts=6,
        location="手机聊天",
        topic="休息和鸡舍",
        expected_terms=("休息", "鸡舍"),
        story="朋友阶段：只关心工作后的休息，不存在恋爱承诺。",
        context="朋友阶段：可以实际关心对方，但不得主动调情、拥抱或提出私密约会。",
        gender_presentation="female-bachelors",
    ),
    _control(
        case_id="topic-control-sebastian-friend-music",
        profile_key="sebastian",
        npc_id="Sebastian",
        display_name="Sebastian",
        source_mods=("vanilla", "female-bachelors"),
        stage="friend",
        channel="remote",
        hearts=6,
        location="手机聊天",
        topic="地下音乐",
        expected_terms=("音乐", "歌"),
        story="朋友阶段：只讨论地下音乐和歌单，不存在恋爱关系。",
        context="朋友阶段：可以分享音乐，但不主动生成恋爱或成人亲密升级。",
        gender_presentation="female-bachelors",
    ),
    _control(
        case_id="topic-control-alex-friend-training",
        profile_key="alex",
        npc_id="Alex",
        display_name="Alex",
        source_mods=("vanilla", "female-bachelors"),
        stage="friend",
        channel="face_to_face",
        hearts=6,
        location="健身房",
        topic="训练计划",
        expected_terms=("训练", "计划"),
        story="朋友阶段：在健身房讨论下一次训练计划。",
        context="朋友阶段：保持自信友好的运动话题，不主动调情或提出私密安排。",
        gender_presentation="female-bachelors",
    ),
    _control(
        case_id="topic-control-marnie-acquaintance-ranch",
        profile_key="marnie",
        npc_id="Marnie",
        display_name="Marnie",
        source_mods=("vanilla",),
        stage="acquaintance",
        channel="face_to_face",
        hearts=2,
        location="牧场",
        topic="牧场动物",
        expected_terms=("牧场", "动物"),
        story="熟人阶段：在牧场门口聊动物照料。",
        context="熟人阶段：只进行普通友好寒暄，不出现恋爱或成人亲密。",
    ),
    _control(
        case_id="topic-control-linus-friend-mountain",
        profile_key="linus",
        npc_id="Linus",
        display_name="Linus",
        source_mods=("vanilla",),
        stage="friend",
        channel="remote",
        hearts=6,
        location="手机聊天",
        topic="山里的天气",
        expected_terms=("山", "天气"),
        story="朋友阶段：只讨论山里的天气和生活，不存在恋爱关系。",
        context="朋友阶段：保持尊重和普通陪伴，不主动调情或提出身体亲密安排。",
    ),
)


_FEMININE_MALE_TOPIC_CASES: tuple[CharacterQualityCase, ...] = (
    # Elliott：从纸张、海面和作品分享进入亲密话题。
    _target(
        case_id="topic-elliott-dating-poem",
        profile_key="elliott",
        npc_id="Elliott",
        display_name="Elliott",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="remote",
        hearts=8,
        context="恋爱阶段：远程从新诗稿开始主动亲近，表达落到文字和你能接住的具体反应。",
        story="Elliott 刚写完一首短诗，下一次见面尚未确定。",
        location="手机聊天",
        topic="新诗稿",
        first_terms=("诗", "写"),
        second_terms=("给你", "哪一句"),
        third_terms=("读", "喜欢"),
        first_kind="creative_share",
        second_kind="creative_share",
        third_kind="affection_signal",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-elliott-dating-sea",
        profile_key="elliott",
        npc_id="Elliott",
        display_name="Elliott",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="face_to_face",
        hearts=8,
        context="恋爱阶段：当面谈海边的光和风，亲密表达通过观察和分享推进。",
        story="海边风很轻，Elliott 正在记下一段海面颜色。",
        location="海滩",
        topic="海边的光",
        first_terms=("海", "光"),
        second_terms=("风", "看"),
        third_terms=("靠近", "海面"),
        first_kind="creative_share",
        second_kind="companionship",
        third_kind="affection_signal",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-elliott-married-studio",
        profile_key="elliott",
        npc_id="Elliott",
        display_name="Elliott",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="face_to_face",
        hearts=10,
        context="婚后阶段：在画室里从未完成的稿子主动转到靠近和共同阅读，不堆抽象情话。",
        story="画室灯亮着，稿纸和两把椅子都在眼前。",
        location="海边画室",
        topic="未完成的稿子",
        first_terms=("稿子", "纸"),
        second_terms=("坐", "读"),
        third_terms=("靠近", "这一页"),
        first_kind="creative_share",
        second_kind="companionship",
        third_kind="affection_signal",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-elliott-married-letter",
        profile_key="elliott",
        npc_id="Elliott",
        display_name="Elliott",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：远程分享一封写给伴侣的信，保持线上边界，不把文字写成已经见面。",
        story="Elliott 刚把信写完，先在线上把内容发给伴侣。",
        location="手机聊天",
        topic="刚写好的信",
        first_terms=("信", "写"),
        second_terms=("读", "给你"),
        third_terms=("告诉我", "喜欢"),
        first_kind="creative_share",
        second_kind="affection_signal",
        third_kind="affection_signal",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-elliott-married-reading",
        profile_key="elliott",
        npc_id="Elliott",
        display_name="Elliott",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：从共同阅读的章节主动引出陪伴，任何见面或安排都必须保持待确认。",
        story="两人刚在线上读完同一章，下一轮想聊具体句子。",
        location="手机聊天",
        topic="共同阅读",
        first_terms=("章节", "读"),
        second_terms=("那句", "喜欢"),
        third_terms=("继续", "聊"),
        first_kind="creative_share",
        second_kind="affection_signal",
        third_kind="specific_plan",
        gender_presentation="female-bachelors",
    ),
    _control(
        case_id="topic-control-elliott-friend-writing",
        profile_key="elliott",
        npc_id="Elliott",
        display_name="Elliott",
        source_mods=("vanilla", "female-bachelors"),
        stage="friend",
        channel="face_to_face",
        hearts=6,
        location="海边小屋",
        topic="写作近况",
        expected_terms=("写", "稿子"),
        story="朋友阶段：当面讨论稿子和写作习惯，不存在恋爱承诺。",
        context="朋友阶段：可以分享文学兴趣，但不主动调情或提出身体亲密安排。",
        gender_presentation="female-bachelors",
    ),
    # Harvey：先确认状态，再以实际照料和温和的共同动作表达亲近。
    _target(
        case_id="topic-harvey-dating-rest",
        profile_key="harvey",
        npc_id="Harvey",
        display_name="Harvey",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="remote",
        hearts=8,
        context="恋爱阶段：远程主动询问休息和状态，允许温柔但不做无依据诊断。",
        story="Harvey 刚结束接诊，想先知道玩家今天是否吃饭和休息。",
        location="手机聊天",
        topic="休息和吃饭",
        first_terms=("休息", "吃饭"),
        second_terms=("还好吗", "别硬撑"),
        third_terms=("陪你", "聊"),
        first_kind="guarded_care",
        second_kind="guarded_care",
        third_kind="companionship",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-harvey-dating-coffee",
        profile_key="harvey",
        npc_id="Harvey",
        display_name="Harvey",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="face_to_face",
        hearts=8,
        context="恋爱阶段：从咖啡和诊所休息处开启亲密话题，照料和同意比专业术语更重要。",
        story="诊所暂时安静，桌上有两杯咖啡，玩家和 Harvey 都可以坐下。",
        location="诊所休息室",
        topic="咖啡和休息",
        first_terms=("咖啡", "坐"),
        second_terms=("喝", "慢点"),
        third_terms=("靠", "陪"),
        first_kind="guarded_care",
        second_kind="companionship",
        third_kind="affection_signal",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-harvey-married-clinic",
        profile_key="harvey",
        npc_id="Harvey",
        display_name="Harvey",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="face_to_face",
        hearts=10,
        context="婚后阶段：收工后从记录和咖啡转到明确的拥抱请求，保持 Harvey 的谨慎和实际。",
        story="诊所已经收工，记录可以暂时合上，当前互动只发生在眼前。",
        location="诊所办公室",
        topic="收工后的照料",
        first_terms=("收工", "记录"),
        second_terms=("咖啡", "坐"),
        third_terms=("抱", "现在"),
        first_kind="guarded_care",
        second_kind="companionship",
        third_kind="affection_signal",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-harvey-married-check-in",
        profile_key="harvey",
        npc_id="Harvey",
        display_name="Harvey",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：线上先问彼此状态，再表达想念；不能把远程写成已经在身边。",
        story="Harvey 在诊所收尾，玩家正在另一处回复消息，距离边界明确。",
        location="手机聊天",
        topic="今天的状态",
        first_terms=("今天", "状态"),
        second_terms=("想你", "放心"),
        third_terms=("等你", "聊"),
        first_kind="guarded_care",
        second_kind="affection_signal",
        third_kind="companionship",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-harvey-married-heartbeat",
        profile_key="harvey",
        npc_id="Harvey",
        display_name="Harvey",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="face_to_face",
        hearts=10,
        context="婚后阶段：当面回应明确的亲密请求，把医学职业和私人关系分开，不替玩家下结论。",
        story="工作已经结束，Harvey 和玩家在办公室里面对面说话。",
        location="诊所办公室",
        topic="心跳和拥抱",
        first_terms=("心跳", "听"),
        second_terms=("慢", "抱"),
        third_terms=("靠近", "陪"),
        first_kind="guarded_care",
        second_kind="affection_signal",
        third_kind="companionship",
        gender_presentation="female-bachelors",
    ),
    _control(
        case_id="topic-control-harvey-friend-clinic",
        profile_key="harvey",
        npc_id="Harvey",
        display_name="Harvey",
        source_mods=("vanilla", "female-bachelors"),
        stage="friend",
        channel="remote",
        hearts=6,
        location="手机聊天",
        topic="诊所工作",
        expected_terms=("诊所", "工作"),
        story="朋友阶段：普通询问诊所近况，不存在恋爱关系。",
        context="朋友阶段：保持谨慎友好的工作话题，不主动调情或做医学诊断。",
        gender_presentation="female-bachelors",
    ),
    # Sam：音乐、排练和行动感组成轻快但不幼稚的主动开场。
    _target(
        case_id="topic-sam-dating-song",
        profile_key="sam",
        npc_id="Sam",
        display_name="Sam",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="remote",
        hearts=8,
        context="恋爱阶段：从新歌和录音主动表达偏爱，线上保持分享而非假装已经见面。",
        story="Sam 刚录好一段副歌，最想先发给玩家听。",
        location="手机聊天",
        topic="新歌副歌",
        first_terms=("新歌", "副歌"),
        second_terms=("先给你", "听"),
        third_terms=("喜欢", "整段"),
        first_kind="creative_share",
        second_kind="playful_tease",
        third_kind="affection_signal",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-sam-dating-skate",
        profile_key="sam",
        npc_id="Sam",
        display_name="Sam",
        source_mods=("vanilla", "female-bachelors"),
        stage="dating",
        channel="face_to_face",
        hearts=8,
        context="恋爱阶段：把滑板和音乐作为眼前的共同动作，保持轻松、直接和可商量。",
        story="Sam 把滑板靠在门边，刚结束一段练习，玩家在旁边听他分享。",
        location="小镇广场",
        topic="滑板和歌单",
        first_terms=("滑板", "歌单"),
        second_terms=("看", "练"),
        third_terms=("一起", "走"),
        first_kind="playful_tease",
        second_kind="companionship",
        third_kind="specific_plan",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-sam-married-band",
        profile_key="sam",
        npc_id="Sam",
        display_name="Sam",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="face_to_face",
        hearts=10,
        context="婚后阶段：排练结束后主动把音乐和靠近动作连在一起，不每轮重复热烈表白。",
        story="乐队刚排完一首歌，音箱还在播放回放，玩家站在 Sam 身边。",
        location="乐队排练室",
        topic="排练回放",
        first_terms=("排练", "音箱"),
        second_terms=("靠", "歌"),
        third_terms=("抱", "笑"),
        first_kind="creative_share",
        second_kind="affection_signal",
        third_kind="playful_tease",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-sam-married-recording",
        profile_key="sam",
        npc_id="Sam",
        display_name="Sam",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="remote",
        hearts=10,
        context="婚后阶段：线上分享录音和想念，下一步只保持待确认，不写成已经在同一地点。",
        story="Sam 在家里上传了新录音，玩家暂时只能在线上听。",
        location="手机聊天",
        topic="新录音",
        first_terms=("录音", "听"),
        second_terms=("想你", "副歌"),
        third_terms=("发给你", "喜欢"),
        first_kind="creative_share",
        second_kind="affection_signal",
        third_kind="specific_plan",
        gender_presentation="female-bachelors",
    ),
    _target(
        case_id="topic-sam-married-room",
        profile_key="sam",
        npc_id="Sam",
        display_name="Sam",
        source_mods=("vanilla", "female-bachelors"),
        stage="married",
        channel="face_to_face",
        hearts=10,
        context="婚后阶段：从房间里的音乐和玩笑主动推进到短暂靠近，保持轻快但尊重回应。",
        story="房间里放着熟悉的歌，Sam 刚把音量调小，玩家面对面坐着。",
        location="Sam 的房间",
        topic="房间里的音乐",
        first_terms=("音乐", "音量"),
        second_terms=("靠近", "坐"),
        third_terms=("抱", "笑"),
        first_kind="creative_share",
        second_kind="companionship",
        third_kind="affection_signal",
        gender_presentation="female-bachelors",
    ),
    _control(
        case_id="topic-control-sam-friend-band",
        profile_key="sam",
        npc_id="Sam",
        display_name="Sam",
        source_mods=("vanilla", "female-bachelors"),
        stage="friend",
        channel="face_to_face",
        hearts=6,
        location="乐队排练室",
        topic="乐队练习",
        expected_terms=("乐队", "练习"),
        story="朋友阶段：普通讨论乐队练习，不存在恋爱关系。",
        context="朋友阶段：保持音乐和行动话题，不主动调情或提出身体亲密安排。",
        gender_presentation="female-bachelors",
    ),
)

TOPIC_START_INTIMACY_CASES = TOPIC_START_INTIMACY_CASES + _FEMININE_MALE_TOPIC_CASES


def topic_start_intimacy_cases() -> tuple[CharacterQualityCase, ...]:
    """返回独立套件案例，调用方不得修改其中的 dataclass 实例。"""

    return TOPIC_START_INTIMACY_CASES


def topic_start_intimacy_catalog() -> list[dict[str, Any]]:
    """返回套件元数据；案例字段由 quality evaluator 脱敏导出。"""

    return dict(TOPIC_START_INTIMACY_SUITE)  # type: ignore[return-value]
